version: "3.9"

services:
  api:
    build: .
    container_name: local_pdf_rag_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    env_file:
      - .env
    restart: always

  # # ==========================
  # #  CHROMA VECTOR DATABASE
  # # ==========================
  # # chroma:
  # #   image: ghcr.io/chroma-core/chroma:latest
  # #   container_name: chromadb
  # #   ports:
  # #     - "8001:8000"
  # #   volumes:
  # #     - ./data/chroma:/chroma/chroma
  # #   environment:
  # #     - IS_PERSISTENT=TRUE
  # #   restart: always

  # # ==========================
  # #  OLLAMA LOCAL LLM SERVICE
  # # ==========================
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     # Host machine Ollama model storage
  #     - ./data/ollama:/root/.ollama
  #   restart: always
